spring:
  cloud:
    function:
      definition: filterArticleSold
    stream:
      bindings:
        filterArticleSold-out-0:
          destination: countryID/marketID/article/sold/filtered/articleID
        filterArticleSold-in-0:
          destination: countryID/marketID/article/sold/register/articleID
      solace:
        bindings:
          filterArticleSold-in-0:
            consumer:
              queueAdditionalSubscriptions: countryID/marketID/article/sold/register/articleID
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'tcps://xxx.messaging.solace.cloud:55443'
                msgVpn: retail-platform
                clientUsername: solace-cloud-client
                clientPassword: xxx
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'

